services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=arka    # Se crea la base de datos arka
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    networks:
#      - arka-microservices
#  arka-users:
#    image: my-springboot-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    networks:
#      - arka-microservices